<template>
    <div class="auth-wrapper">
        <h2 class="lgn-sgnup-txt">Reset Password</h2>
        <form @submit.prevent="handleSubmit" class="auth-form">
            <input v-model="newPassword"     type="password" placeholder="New password (8+ chars)"  class="auth-input" required />
            <!--
              @keydown.enter.prevent on the second field so pressing Enter
              there submits the form instead of doing nothing.
            -->
            <input v-model="confirmPassword" type="password" placeholder="Confirm new password"     class="auth-input" required @keydown.enter.prevent="handleSubmit" />
            <button type="submit" class="auth-button button-size" :disabled="loading">
                {{ loading ? 'Resetting...' : 'Reset Password' }}
            </button>
        </form>

        <!-- Success message (green) — shown before the redirect countdown -->
        <p v-if="success" class="auth-error" style="color:#4caf50;">{{ success }}</p>
        <!-- Validation or server error message -->
        <p v-if="error"   class="auth-error">{{ error }}</p>
    </div>
</template>

<script setup>
// =============================================================================
// ResetPassword.vue — password reset completion page
//
// The second step of the two-page password reset flow:
//   1. ForgotPassword.vue → backend sends email with /reset-password/:token link
//   2. User clicks the link → lands here → submits new password
//
// The :token route param is a one-time, time-limited JWT or random string
// generated by the backend when the reset request was made. It is passed
// directly in the POST request URL so the backend can validate it and
// identify the associated account.
//
// Client-side validation:
//   - Passwords must match (checked before any API call)
//   - Password must be at least 8 characters
//
// On success, the user sees a confirmation message and is automatically
// redirected to /login after 2 seconds.
// =============================================================================

import { ref } from 'vue';
import { useRoute } from 'vue-router';
import axios from 'axios';

// Base URL for user API endpoints
const API_URL = import.meta.env.VITE_API_URL + '/api/users';

// useRoute gives access to the :token dynamic segment of /reset-password/:token
const route = useRoute();

// ── Local state ────────────────────────────────────────────────────────────────

const newPassword     = ref(''); // First password field
const confirmPassword = ref(''); // Confirmation field — must match newPassword
const loading         = ref(false);
const success         = ref('');
const error           = ref('');

// ── Form submission ────────────────────────────────────────────────────────────

/**
 * Validates the two password fields, then POSTs the new password along with
 * the token from the URL to the reset-password endpoint.
 *
 * Validation order:
 *   1. Passwords must match
 *   2. Password must be at least 8 characters
 * Both checks happen client-side to give immediate feedback without a round-trip.
 *
 * On success: shows a "Redirecting..." message and navigates to /login after 2 s.
 * On failure: shows the server's error (e.g. "Token has expired.").
 */
const handleSubmit = async () => {
    error.value = '';

    // Client-side validation: both fields must match
    if (newPassword.value !== confirmPassword.value) {
        error.value = 'Passwords do not match.';
        return;
    }
    // Client-side validation: enforce minimum length before hitting the server
    if (newPassword.value.length < 8) {
        error.value = 'Password must be at least 8 characters.';
        return;
    }

    loading.value = true;
    try {
        // The token is extracted from the dynamic route param :token
        const res = await axios.post(`${API_URL}/reset-password/${route.params.token}`, {
            newPassword: newPassword.value,
        });
        // Append a redirect notice to whatever message the server returned
        success.value = res.data.message + ' Redirecting to login...';
        // Redirect after a short delay so the user can read the success message
        setTimeout(() => { window.location.href = '/login'; }, 2000);
    } catch (err) {
        error.value = err.response?.data?.message || 'Invalid or expired link.';
    } finally {
        loading.value = false;
    }
};
</script>
